# Generated by Django 6.0.1 on 2026-01-28 21:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, help_text='To be taken orally etc.', max_length=100)),
                ('schedule', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMedicationAdministrationRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('administered_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('GIVEN', 'Given'), ('REFUSED', 'Refused'), ('PARTIAL', 'Partially Taken'), ('NOT_AVAILABLE', 'Not available'), ('HELD', 'Held (Clinical decision)')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('edit_reason_type', models.CharField(blank=True, choices=[('TYPO', 'Typo / Spelling Correction'), ('LATE_ENTRY', 'Late Entry'), ('CLARIFICATION', 'Clarification')], max_length=20)),
                ('edit_reason_detail', models.CharField(blank=True, help_text='Reason for last edit (e.g. typo correction, late entry)', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('administered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.medication')),
            ],
            options={
                'verbose_name': 'historical medication administration record',
                'verbose_name_plural': 'historical medication administration records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MedicationAdministrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('GIVEN', 'Given'), ('REFUSED', 'Refused'), ('PARTIAL', 'Partially Taken'), ('NOT_AVAILABLE', 'Not available'), ('HELD', 'Held (Clinical decision)')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('edit_reason_type', models.CharField(blank=True, choices=[('TYPO', 'Typo / Spelling Correction'), ('LATE_ENTRY', 'Late Entry'), ('CLARIFICATION', 'Clarification')], max_length=20)),
                ('edit_reason_detail', models.CharField(blank=True, help_text='Reason for last edit (e.g. typo correction, late entry)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='med_admins', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='core.medication')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='core.resident'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('SAFEGUARDING', 'safeguarding'), ('MISSING', 'Missing from home'), ('SELF_HARM', 'Self-harm'), ('AGGRESSION', 'Aggression'), ('PROPERTY', 'Property damage'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=10)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('external_contacts', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edit_reason_type', models.CharField(blank=True, choices=[('TYPO', 'Typo / Spelling Correction'), ('LATE_ENTRY', 'Late Entry'), ('CLARIFICATION', 'Clarification')], max_length=20)),
                ('edit_reason_detail', models.CharField(blank=True, help_text='Reason for last edit (e.g. typo correction, late entry.)', max_length=255)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.resident')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('SAFEGUARDING', 'safeguarding'), ('MISSING', 'Missing from home'), ('SELF_HARM', 'Self-harm'), ('AGGRESSION', 'Aggression'), ('PROPERTY', 'Property damage'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=10)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('external_contacts', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('edit_reason_type', models.CharField(blank=True, choices=[('TYPO', 'Typo / Spelling Correction'), ('LATE_ENTRY', 'Late Entry'), ('CLARIFICATION', 'Clarification')], max_length=20)),
                ('edit_reason_detail', models.CharField(blank=True, help_text='Reason for last edit (e.g. typo correction, late entry.)', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.resident')),
            ],
            options={
                'verbose_name': 'historical incident',
                'verbose_name_plural': 'historical incidents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('triggers', models.TextField(blank=True)),
                ('deescalation_strategies', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='core.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('DAY', 'Day'), ('LATE', 'Late'), ('NIGHT', 'Night')], max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('handover_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ManyToManyField(related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDailyLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('summary', models.TextField()),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('interventions', models.TextField(blank=True)),
                ('event_at', models.DateTimeField(blank=True, help_text='When the event/observation actually occurred.', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='Server time when this was recorded.', null=True)),
                ('edit_reason_type', models.CharField(blank=True, choices=[('TYPO', 'Typo / Spelling Correction'), ('LATE_ENTRY', 'Late Entry'), ('CLARIFICATION', 'Clarification')], help_text='Structured reason code for amendments / late entry justification.', max_length=32, null=True)),
                ('edit_reason_detail', models.TextField(blank=True, default='', help_text='Free text explanation required for meaningful amendments / late entry justification.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.resident')),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.shift')),
            ],
            options={
                'verbose_name': 'historical daily log',
                'verbose_name_plural': 'historical daily logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('interventions', models.TextField(blank=True)),
                ('event_at', models.DateTimeField(blank=True, help_text='When the event/observation actually occurred.', null=True)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='Server time when this was recorded.', null=True)),
                ('edit_reason_type', models.CharField(blank=True, choices=[('TYPO', 'Typo / Spelling Correction'), ('LATE_ENTRY', 'Late Entry'), ('CLARIFICATION', 'Clarification')], help_text='Structured reason code for amendments / late entry justification.', max_length=32, null=True)),
                ('edit_reason_detail', models.TextField(blank=True, default='', help_text='Free text explanation required for meaningful amendments / late entry justification.')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_log', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='core.resident')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shift')),
            ],
        ),
    ]
