# Generated by Django 6.0.1 on 2026-01-13 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('DAY', 'Day'), ('LATE', 'Late'), ('NIGHT', 'Night')], max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('handover_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ManyToManyField(related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
