# Generated by Django 6.0.1 on 2026-01-13 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('SAFEGUARDING', 'safeguarding'), ('MISSING', 'Missing from home'), ('SELF_HARM', 'Self-harm'), ('AGGRESSION', 'Aggression'), ('PROPERTY', 'Property damage'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=10)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('external_contacts', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.resident')),
            ],
        ),
    ]
