# Generated by Django 6.0.1 on 2026-01-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(blank=True)),
                ('triggers', models.TextField(blank=True)),
                ('deescalation_strategies', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='core.resident')),
            ],
        ),
    ]
