# Generated by Django 6.0.1 on 2026-01-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalincident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='last_edit_reason',
            field=models.CharField(blank=True, help_text='Reason for last edit (e.g. typo correction, late entry.)', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalmedicationadministrationrecord',
            name='last_edit_reason',
            field=models.CharField(blank=True, help_text='Reason for last edit (e.g. typo correction, late entry)', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_edit_reason',
            field=models.CharField(blank=True, help_text='Reason for last edit (e.g. typo correction, late entry.)', max_length=255),
        ),
        migrations.AddField(
            model_name='medicationadministrationrecord',
            name='last_edit_reason',
            field=models.CharField(blank=True, help_text='Reason for last edit (e.g. typo correction, late entry)', max_length=255),
        ),
    ]
