# Generated by Django 6.0.1 on 2026-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicalincident_last_edit_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='last_edit_reason_code',
            field=models.CharField(blank=True, choices=[('TYPO', 'Typo / Spelling Correction'), ('LATE_ENTRY', 'Late Entry'), ('CLARIFICATION', 'Clarification')], max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_edit_reason_code',
            field=models.CharField(blank=True, choices=[('TYPO', 'Typo / Spelling Correction'), ('LATE_ENTRY', 'Late Entry'), ('CLARIFICATION', 'Clarification')], max_length=20),
        ),
    ]
