# Generated by Django 6.0.1 on 2026-01-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicalmedicationadministrationrecord_last_edit_reason_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalincident',
            old_name='last_edit_reason',
            new_name='edit_reason_detail',
        ),
        migrations.RenameField(
            model_name='historicalincident',
            old_name='last_edit_reason_code',
            new_name='edit_reason_type',
        ),
        migrations.RenameField(
            model_name='historicalmedicationadministrationrecord',
            old_name='last_edit_reason',
            new_name='edit_reason_detail',
        ),
        migrations.RenameField(
            model_name='historicalmedicationadministrationrecord',
            old_name='last_edit_reason_code',
            new_name='edit_reason_type',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='last_edit_reason',
            new_name='edit_reason_detail',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='last_edit_reason_code',
            new_name='edit_reason_type',
        ),
        migrations.RenameField(
            model_name='medicationadministrationrecord',
            old_name='last_edit_reason',
            new_name='edit_reason_detail',
        ),
        migrations.RenameField(
            model_name='medicationadministrationrecord',
            old_name='last_edit_reason_code',
            new_name='edit_reason_type',
        ),
    ]
